name: CI - Quality Checks

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Test
        run: echo 'Add quality checks here'
